import React from 'react'
import "./portfolio.css"
import Project from './project'
import Portfolio1 from '../assets/TriviaGame.png'
import Portfolio2 from '../assets/Tenzies.png'
import Portfolio3 from '../assets/MemeGenerator.png'
import Portfolio4 from '../assets/CryptoToken.png'

export default function Portfolio(){
    return (
        <section id='portfolio'>
            <h5>My Recent Work</h5>
            <h2 className='trans'>Projects</h2>
            <div className='projects'>
                <Project img={Portfolio1} title={"Trivia Game"} desc={"A trivia game in which the user can select from the main page the category (eg. mythology, mathematics, etc.), the number of questions, the difficulty and the option for the questions to be grid-type or true-or-false. The questions are generated by an API and will be displayed according to the chosen criteria. After finishing the test and pressing the 'Check' button, the correct answers and the number of correct answers of the user will be displayed on the screen."}/>
                <Project img={Portfolio3} title={"Meme Generator"} desc={"A meme generator where the user can create his own meme. Through an API, random images will be generated every time the user presses a button. You can also insert two suggestive descriptions of the image to make the meme more suggestive."}/>
                <Project img={Portfolio2} title={"Tenzies"} desc={"A game of Tenzies. The idea of the game is to get the same number on all the dice in as few attempts as possible. The dice can be locked by selecting them so that they do not change their value when the 'Roll' button is pressed. When all the dice are locked and have the same displayed value, the game is over and the user can start a new game."}/>
                <Project img={Portfolio4} title={"Crypto Token"} desc={"A token named DARK in Internet Computer blockchain, using react as frontend and motoko as database. Each user will have a unique username for the device used. To check the username, the user can press the 'Check account' button in the second box. Each user can receive 1000 free DARK tokens by pressing the button in the first box. Users can check the number of tokens they have in their account by clicking on the button in the third box. Also, in the last box, the user can make a transfer to another account."}/>
            </div>
            <p className='space'></p>
            <a className='btn trans' href="https://github.com" target="_blank">Check more projects on Github</a>
            <p className='space'></p>
        </section>
    )
}